### ISSUE TITLE
Error during compile against ZNC 1.5-git-257-0908023

### ISSUE THREAD

**Issue by fred0r** [mmilata/znc-otr#25]
I get the following error during compile with a recent 1.5-znc-git

znc-otr-master$ make
LIBS="-lotr" znc-buildmod otr.cpp
Building "otr.so" for ZNC 1.5... In file included from /home/znc/include/znc/Socket.h:22:0,
                 from /home/znc/include/znc/Client.h:21,
                 from /home/znc/include/znc/znc.h:21,
                 from /home/znc/include/znc/IRCNetwork.h:24,
                 from otr.cpp:17:
/home/znc/include/znc/Threads.h: In member function ‘void COtrMod::GenerateKey(bool)’:
/home/znc/include/znc/Threads.h:113:2: error: ‘CMutexLocker::CMutexLocker(const CMutexLocker&)’ is private
otr.cpp:216:57: error: within this context
In file included from /home/znc/include/znc/Socket.h:22:0,
                 from /home/znc/include/znc/Client.h:21,
                 from /home/znc/include/znc/znc.h:21,
                 from /home/znc/include/znc/IRCNetwork.h:24,
                 from otr.cpp:17:
/home/znc/include/znc/Threads.h: In member function ‘virtual bool COtrMod::OnLoad(const CString&, CString&)’:
/home/znc/include/znc/Threads.h:76:10: error: ‘CMutex& CMutex::operator=(const CMutex&)’ is private
otr.cpp:585:26: error: within this context
In file included from /home/znc/include/znc/Socket.h:22:0,
                 from /home/znc/include/znc/Client.h:21,
                 from /home/znc/include/znc/znc.h:21,
                 from /home/znc/include/znc/IRCNetwork.h:24,
                 from otr.cpp:17:
/home/znc/include/znc/Threads.h: In static member function ‘static void\* COtrMod::GenKeyThreadFunc(void_)’:
/home/znc/include/znc/Threads.h:113:2: error: ‘CMutexLocker::CMutexLocker(const CMutexLocker&)’ is private
otr.cpp:838:62: error: within this context
In file included from /home/znc/include/znc/Socket.h:22:0,
                 from /home/znc/include/znc/Client.h:21,
                 from /home/znc/include/znc/znc.h:21,
                 from /home/znc/include/znc/IRCNetwork.h:24,
                 from otr.cpp:17:
/home/znc/include/znc/Threads.h: In member function ‘virtual void COtrGenKeyTimer::RunJob()’:
/home/znc/include/znc/Threads.h:113:2: error: ‘CMutexLocker::CMutexLocker(const CMutexLocker&)’ is private
otr.cpp:1193:61: error: within this context
[ !! ] Error while building "otr.so"
make: *_\* [otr.so] Fehler 1
